/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.myapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
@SpringBootApplication
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @GetMapping("/hi")
    public String hello(String name) {
        return "hi";
    }

    @GetMapping("/help") // "/help" URL 요청을 help.html 템플릿으로 매핑
    public String help() {
        return "help"; // templates/help.html 파일을 렌더링
    }
}
